### ISSUE TITLE
org-planning-line-re

### ISSUE THREAD

**Issue by gambhiro** [remyhonig/elfeed-org#11]
Cool way of organizing the feeds!

When I called `elfeed` I got this error:

```
org-element-headline-parser: Symbol's value as variable is void: org-planning-line-re
```

Adding `(setq org-planning-line-re "")` to the init commands fixed it, although I suspect there must be a more proper way of dealing with it.

```
emacs-version
GNU Emacs 25.0.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.12) of 2015-04-19 on lgw01-11

org-version
Org-mode version 8.2.10 (8.2.10-41-g42228a-elpa @ /usr/local/share/emacs/site-lisp/org/)
```

**Comment by remyhonig** [comment]
Thanks for opening an issue! It might be a while before I come back to fix this though because I have to find out how I can test Emacs 25 with Travis and I don't have a lot of time at the moment. I'll let you know when I eventually get to it.

**Comment by gambhiro** [comment]
Ah, false alert, sorry. The problem was in the daily-snapshot org-mode from melpa.

I compiled the latest stable release 8.2.10 (Oct. 2014) and now elfeed starts with no errors.

```
Org-mode version 8.2.10 (release_8.2.10 @ /usr/local/share/emacs/site-lisp/org/)
```

**Comment by remyhonig** [comment]
No problem, thanks for cleaning up.
