### ISSUE TITLE
Parse org links

### ISSUE THREAD

**Issue by justmytwospence** [remyhonig/elfeed-org#12]
It would be great if, instead of having to start with `http`, elfeed-org would also allow you to specifify an org link on the headline, eg: `[[link][description]]`. This would make elfeed.org files *much* easier to read.

**Comment by remyhonig** [comment]
I like the idea. In a next iteration of the package I'll add this. It might take a while tough before I'll work on this again. I'll update this issue when I start working on it.

**Comment by justmytwospence** [comment]
Thanks for looking at it. I noticed you reverted #14, I'm assuming because it seemed to break tagging. Any way I can help figure that out?

**Comment by remyhonig** [comment]
You're right. I broke it and I didn't notice the tags not being updated anymore. In https://github.com/remyhonig/elfeed-org/pull/16 I'll re-add the org mode link support but this time with more test coverage. Thanks for offering to help though!
