### ISSUE TITLE
no more tags

### ISSUE THREAD

**Issue by heikkil** [remyhonig/elfeed-org#15]
After recent bulk package upgrade, elfeed does not create any entry tags any more from elfeed.org tags. Entries are still there but no tags. Isn't  this happening to everyone?

**Comment by remyhonig** [comment]
I can confirm this, I will revert back the breaking change! My apologies.

**Comment by remyhonig** [comment]
As soon as the revert is propagated to MELPA the tags should work again after you upgrade the package. You can check here if is available https://melpa.org/#/elfeed-org  (version with the broken tags is 20150927.1315 so yo should wait for a newer version)

**Comment by heikkil** [comment]
Thanks!

Good to know it was not me twiddling my emacs conf. :)
