### ISSUE TITLE
[feature] :title meta-data suport for feeds

### ISSUE THREAD

**Issue by groks** [remyhonig/elfeed-org#19]
Some feeds have long, uninformative, or no titles at all. There's an issue for feed renaming (skeeto/elfeed/issues/78) and support has been added for the :title property on feeds.

How about this feature for elfeed-org: if you use an Org link to define the feed then use the link description to set the :title property.

    * Feeds :elfeed:
    ** [[http://example.com][This Becomes The Feed Title]] :atag:
    ** http://example.com/use-default-feed-title

**Comment by remyhonig** [comment]
I like this suggestion. When I have some time I'll certainly implement this.

**Comment by Distopico** [comment]
+10 great feature

**Comment by Kungsgeten** [comment]
I thought it was a good idea too, so I had a go at it and have submitted a pull request.

**Comment by remyhonig** [comment]
Thanks a lot for submitting your PR! I'm afraid it did not pass one of the tests though. Could you take a look at the test results and try to solve it?

**Comment by Kungsgeten** [comment]
I'll comment on the PR instead of this issue.

**Comment by remyhonig** [comment]
@Kungsgeten added this feature for us! See the `README` for usage.
