### ISSUE TITLE
[bug] Update .org no index in elfeed

### ISSUE THREAD

**Issue by Distopico** [remyhonig/elfeed-org#20]
Sometimes I have to clean the data to index content when the tags are changed or for test, use elfeed-org and sometimes to update the list in .org and run elfeed-org but not updated content and feed in *elfeed-search *, I have been clean elfeed-db.el variables and delete the directory for update.

**Comment by remyhonig** [comment]
Thank you for your bug report. Could you help me with this and give me the exact steps to reproduce it? It would help me a lot if you'd state 1. the steps to reproduce. 2. the expected behavior and 3. the actual behavior.

**Comment by Distopico** [comment]
Hi, thanks for you answer, 

1) I edit elfeed.org and I add new feeds and I change some tags, run: M-x elfeed-org for update feeds list

2) I go to elfeed buffer, and run: M-x elfeed-update()  and i don't see my changes, the buffer has same tags and no have the new feed, I try elfeed-search-update--force and nothing happens

3) I expect edit my feeds in elfeed.org and see reflected the changes in the buffer after run: M-x elffed-org  and elfeed-update()

**Comment by remyhonig** [comment]
I see what you mean. Well I can give you 2 workarounds:

Option 1: Save your org file and restart emacs.

Option 2: 
  - M-x -> eval-expression -> (rmh-elfeed-org-process rmh-elfeed-org-files rmh-elfeed-org-tree-id) 
  - M-x -> elfeed-update

Let me know if this works for you.

**Comment by Distopico** [comment]
The first option I already used, is not useful when working and have many files with projects open and need add some feed and read later.

But the second option worked perfect for me, thank you for you help :)

**Comment by remyhonig** [comment]
I'm glad I could help :+1:
