### ISSUE TITLE
import from ttrss into elfeed-org suggestions?

### ISSUE THREAD

**Issue by zeltak** [remyhonig/elfeed-org#25]
Hi!

thx for your great work! im in the process of trying to move from ttrss to elfeed. i have 100's of feeds and would prefer not to enter them manually :D . Is there anyway you know or can suggest of importing these feeds into the elfeed-org format?

thx!

Z

**Comment by remyhonig** [comment]
Hi, and thank you! I think you can export your feeds as an OPML file from ttrss. When you have that file you can try the approach described in http://www.massplanner.com/knowledgebase/extracting-multiple-rss-feeds-from-opml-to-use-in-mass-planner/ to extract the feed urls and then it should be easy to create a tree structure from it in org-mode. Hope this helps.

**Comment by zeltak** [comment]
thx alot @remyhonig!

this is perfect

best

Z
