### ISSUE TITLE
Org package being installed, but I run my own from source

### ISSUE THREAD

**Issue by wdenton** [remyhonig/elfeed-org#37]
I compile Org from source and run that version, so I don't use or need the packaged Org, but it's required here, so installing elfeed-org forces the older version of Org on me. Of course elfeed-org needs Org to work, but is it necessary to force it to be installed, or is there some way of avoiding this?

**Comment by remyhonig** [comment]
Probably but I don't know how. This this is too much of an edge case to keep this ticket open. You are of course always free to open a feature request.
