### ISSUE TITLE
elfeed-org loaded 0 feeds, 0 rules

### ISSUE THREAD

**Issue by raamdev** [remyhonig/elfeed-org#4]
I'm using Emacs 24.4.1 and trying to get `elfeed-org` working but after installing through MELPA and setting up my config as per the readme here on GitHub, I always just get the following message when I run `M-x elfeed`:

```
elfeed-org loaded 0 feeds, 0 rules
```

Here's the `elfeed-org` config in my `~/.emacs.d/init.el`:

``` lisp
;; This hooks up elfeed-org to read the configuration when elfeed
;; is started with =M-x elfeed=
(require 'elfeed-org)

;; Initialize elfeed-org
(elfeed-org)

;; Optionally specify a number of files containing elfeed
;; configuration. If not set then the location below is used.
(setq rmh-elfeed-org-files (list "~/.emacs.d/elfeed.org"))
(setq rmh-elfeed-org-tree-id "elfeed")
```

And here's my `~/.emacs.d/elfeed.org`:

```
* Technology                                   :tech:
 :PROPERTIES:
 :ID: elfeed
 :END:
  * http://www.terminally-incoherent.com/blog/feed
```

---

Any idea what might be going on? Or is there anything I can do to attempt to troubleshoot this? (I'm relatively new to Emacs, so I'm still learning the ropes.)

**Comment by rafaelleru** [comment]
Hi, I'm getting the same issue with org-bullets-mode and I can't fix it. Any other help?
