### ISSUE TITLE
Can't populate elfeed.org file

### ISSUE THREAD

**Issue by tinfoilhatter** [remyhonig/elfeed-org#41]
I'm currently unable to fill my **elfeed.org** file with my feeds from the **elfeed-feeds** variable in my **.emacs** file. That variable was created directly by **elfeed** after I loaded an OPML file and added a few feeds with the **elfeed-add-feed** command. It works just fine, but when I use the **elfeed-org** package, it doesn't save them to **elfeed.org**, and then the next time I start Emacs and try to find new items with G, it does nothing. Checking **elfeed.org** then reveals it to be empty.

As of this writing, I'm running the latest Emacs in Ubuntu 17.10, and all the latest packages. Here is my **use-package** declaration from **.emacs**. It's commented out because of the behavior detailed above. Thanks.

````
;; use an org file to organise feeds
;; (use-package elfeed-org
;;   :ensure t
;;   :config
;;   (elfeed-org)
;;   (setq rmh-elfeed-org-files (list "~/elfeed.org")))
````

**Comment by tinfoilhatter** [comment]
As often happens, explaining my issue helped me understand it better myself. I used the command **elfeed-org-import-opml** to create a buffer with an Org version of my OPML file in it, then manually copied the buffer contents to **elfeed.org**. It seems to work. However, now all my feeds are named "nil" (as when I used the command before). I have over 420 feeds. Is there any way to update their names in **elfeed.org** automatically?

**Comment by teunzwart** [comment]
Not a fix, but a workaround. Given an opml file we can extract the feed urls and titles using the following Python code:
```
from bs4 import BeautifulSoup

with open("feeds.opml") as data:
    soup = BeautifulSoup(data.read(), "lxml")
    for feed in soup.find_all("outline"):
        print(f"[[{feed.get('xmlurl')}][{feed.get('text')}]]")
```
This will print the feeds to the terminal in the correct format for easy copy-pasting into an org file. Note that it also adds entries with empty urls for any folders into which you may have put them. Not perfect but better than entering feeds by hand.
