### ISSUE TITLE
Error (use-package): Failed to install elfeed-org: Package ‘org-8.2.7’ is unavailable

### ISSUE THREAD

**Issue by pille1842** [remyhonig/elfeed-org#45]
I'm getting the above error with the following configuration:

```elisp
(use-package elfeed-org
    :ensure t
    :config
    (elfeed-org)
    (setq rmh-elfeed-org-files (list "~/org/feeds.org")))
```

My Emacs version is `GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-12`, Org-mode is `Org-mode version 8.2.10 (release_8.2.10 @ /usr/share/emacs/25.3/lisp/org/)`.

Is there any way to make elfeed-org's requirements less specific? It requires Org 8.2.7 and 8.2.10, it seems to me, is pretty close to that. I would like to avoid installing elfeed-org manually and changing the requirement myself, if possible.

**Comment by remyhonig** [comment]
My understanding is that the version `8.2.10` would be valid because it is greater than `8.2.7`. I'd gladly change it for you, but I don't have any time to fix it myself. If you give me a PR that will not break anything I'll merge it ASAP. I cannot see the error message you mention though.

**Comment by voteleobrown** [comment]
I'm having the same problem.

**Comment by lyr3** [comment]
Same here!

**Comment by voteleobrown** [comment]
The text of that error message isn't in the .el...where does it even come from? How is a requirement like that set?

**Comment by lyr3** [comment]
@voteleobrown It is working...don't know why!

**Comment by MathanGeurtsen** [comment]
I have the same problem, I'll look into fixing it, but I'm an elisp noob, so that's gonna take a while.

**Comment by voteleobrown** [comment]
@lyr3 I'm still having the problem.

**Comment by voteleobrown** [comment]
I'm running Emacs 25.2.2 and org 8.2.10, which should both be within your testing window.

**Comment by lyr3** [comment]
@voteleobrown i disabled it for now! /:

**Comment by teunzwart** [comment]
I managed to fix this by adding the org repository to my `init.el`: 
```
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))
```
and then downloading the latest version of org by looking for it in `package-list-packages`.

**Comment by remyhonig** [comment]
I trust the last comment is the fix for this problem. Closing this ticket for now.
