### ISSUE TITLE
Cannot open org file in media folder

### ISSUE THREAD

**Issue by RidaAyed** [remyhonig/elfeed-org#51]
Somehow I can't manage too use my org file which resides in the `/media/`  folder and is used daily in emacs

    rmh-elfeed-org-check-configuration-file: Elfeed-org cannot open /media/sf_Documents/Dropbox/my.org
    Make sure it exists or customize the variable ’rmh-elfeed-org-files’

The same file in `/home/user/` works

Any ideas how I can use the file in the `/media/` folder?

P.S. Thank you for that useful package :clap:

**Comment by remyhonig** [comment]
Hi @RidaAyed, it is nice to hear this package helps you! 

Make sure you configured elfeed-org like this:

```
;; Optionally specify a number of files containing elfeed
;; configuration. If not set then the location below is used.
;; Note: The customize interface is also supported.
(setq rmh-elfeed-org-files (list "~/.emacs.d/elfeed.org"))
```

Or is you use spacemacs see http://spacemacs.org/layers/+web-services/elfeed/README.html

My first thought is that something is wrong with the permissions on your file. Let me know if you find out there is something wrong with the code, then we'll make a bug of this ticket.
