### ISSUE TITLE
FEATURE: Elfeed entries to org file

### ISSUE THREAD

**Issue by SidharthArya** [remyhonig/elfeed-org#52]
I am aware that this package is supposed to read an org file with rss links and add them to `elfeed-urls` but would it be possible to also have a few interactive functions which can mark a few entries and send them to an org file for future references?

**Comment by JohnJohnstone** [comment]
You could use org-capture. There is a great article descibing a workflow here http://heikkil.github.io/blog/2015/05/09/notes-from-elfeed-entries/
