### ISSUE TITLE
Help:  Looking for more documentation on entry-title option

### ISSUE THREAD

**Issue by shanff** [remyhonig/elfeed-org#53]
Like the subject says, I guess I'm misunderstanding what I can do with the entry-title and how  I can leverage it to re-tag items.

What is it attempting to match with regex, the feed name, the subject of post, other?  How can I pull up the details of the post to validate what I'm looking at?

A for instance:

I'm wanting to follow Sacha Chua via RSS, but :ignore: her "Weekly review" posts as they're more personal and have less to do with Emacs.

I did something like the following, but not seeing what I'm expecting.

    * News                                                               :elfeed:
    ** entry-title: \(linux\|linus\|ubuntu\|kde\|gnome\)                  :linux:
    ** entry-title: \(Weekly\-review\)                                    :ignore:
    *** Emacs                                                             :emacs:
    **** https://www.reddit.com/r/emacs/.rss                             :reddit:
    **** https://sachachua.com/blog/feed/
    ** Software Development                                                :dev:
    *** Python                                                           
    **** https://www.reddit.com/r/python/.rss                            :reddit:

It's not tagging anything with ignore, and actually, it  blocks everything except for Python for some reason.

Any pointers?

**Comment by remyhonig** [comment]
It is not explicitly stated in the documentation, but the `:ignore:` tag only works on the entire feed and not on keywords in titles. `entry-title` works only on the post subjects.

So unfortunately your use case is currently not supported by this package.

**Comment by shanff** [comment]
Good 'nuff.  Thanks for the clarification.
