### ISSUE TITLE
Feed won't update

### ISSUE THREAD

**Issue by jarss** [remyhonig/elfeed-org#54]
I've installed elfeed and elfeed-org, but I can't get it to update. Keeps saying database is empty. This is also a problem when I try elfeed itself (without activating elfeed-org). 

I use org for my settings. Here's what I have in: 

```
#+BEGIN_SRC emacs-lisp
(require 'elfeed-org)
(elfeed-org)
(setq rmh-elfeed-org-files (list "/mnt/veracrypt1/Personal/feeds.org"))
#+END_SRC
```

and in feeds.org:

```
* Blogs                     
** https://irreal.org/blog/?s=rss2                                    :emacs:
** https://www.rousette.org.uk/index.xml
```
It seems to find the files OK and I get no errors, but it doesn't update. I believe I have the right links (tried several) for RSS. What should I check next?

**Comment by jarss** [comment]
OK, elfeed works now, but elfeed-org still doesn't load any articles. Not sure why.

**Comment by nguyenhaiac** [comment]
Can you try to add elfeed tags to the headline. I've done the same and it's working now.

**Comment by firmart** [comment]
Put the tag `:elfeed:` to the top-level headlines.
