### ISSUE TITLE
mapc: Symbol’s function definition is void: org--check-org-structure-template-alist in Emacs 27.1

### ISSUE THREAD

**Issue by gbiscuolo** [remyhonig/elfeed-org#56]
After my last upgrade to Emacs 27.1 (using Guix as package manager on foreign distro) I get this error in the Messages buffer when I try to "M-x elfeed":

  mapc: Symbol’s function definition is void: org--check-org-structure-template-alist

This is the backtrace:

```

Debugger entered--Lisp error: (void-function org--check-org-structure-template-alist)
  org--check-org-structure-template-alist(org-structure-template-alist)
  mapc(org--check-org-structure-template-alist (org-structure-template-alist org-tempo-keywords-alist))
  org-tempo-add-templates()
  org-tempo--update-maybe()
  org-tempo-setup()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  #f(compiled-function (file) #<bytecode 0x10396bd>)("~/.emacs.d/elfeed.org")
  #f(compiled-function (it) #<bytecode 0x2ba910d>)("~/.emacs.d/elfeed.org")
  mapcar(#f(compiled-function (it) #<bytecode 0x2ba910d>) ("~/.emacs.d/elfeed.org"))
  -mapcat(#f(compiled-function (file) #<bytecode 0x10396bd>) ("~/.emacs.d/elfeed.org"))
  rmh-elfeed-org-import-headlines-from-files(("~/.emacs.d/elfeed.org") "elfeed")
  rmh-elfeed-org-process(("~/.emacs.d/elfeed.org") "elfeed")
  ad-Advice-elfeed(#f(compiled-function () (interactive nil) #<bytecode 0x1012e69>))
  apply(ad-Advice-elfeed #f(compiled-function () (interactive nil) #<bytecode 0x1012e69>) nil)
  elfeed()
  funcall-interactively(elfeed)
  call-interactively(elfeed record nil)
  command-execute(elfeed record)
  execute-extended-command(nil "elfeed" nil)
  funcall-interactively(execute-extended-command nil "elfeed" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```

I confirm that rolling back to 26.3 all works as usual.

Thanks! Gio'

**Comment by remyhonig** [comment]
Thank you for your report! I am afraid I do not have time to look into it though. But that org-tempo-setup() call does seem a bit out of place.

**Comment by gbiscuolo** [comment]
> Thank you for your report! I am afraid I do not have time to look into it though. But that org-tempo-setup() call does seem a bit out of place.

After some investigation I realized I was mix-and-match-ing Emacs packages from 26.3 and 27.1: when I solved that (removed `~/.emacs.d/elpa`), this issue disappeared. Details on https://issues.guix.gnu.org/issue/43243.

I'm closing this bug now, sorry for the noise!

Happy hacking! Giovanni.

**Comment by remyhonig** [comment]
Thanks for the follow up! No problem at all, Guix looks interesting, I should try that one day.
