### ISSUE TITLE
Doesn't filter trees with `:ID: elfeed` property

### ISSUE THREAD

**Issue by leafac** [remyhonig/elfeed-org#6]
I have the following Org file:

```
* I should not be fetched, but am:
** http://example.com
* I'm fetched just fine
  :PROPERTIES:
  :ID:       elfeed
  :END:
** http://gdata.youtube.com/feeds/base/users/portadosfundos/uploads?alt=rss&v=2&orderby=published&client=ytapi-youtube-profile
```

From what I understand, only the second link should be added to elfeed's list. But that's not what happens. In fact, elfeed tries to fetch the first link and fails with `Elfeed update failed for http://example.com: (error XML: (Well-Formed) Invalid character)`.

[Org Mode manual](http://orgmode.org/manual/Special-properties.html#Special-properties) states that `:ID:` is a special property key and should not be used. Maybe that has to do with the error.

---

I'm new to Elisp, so I'm having trouble to debug this myself. But I would love to help fixing the issue.

Other than this, I'm looking forward into using this extension to elfeed!

Best.

**Comment by remyhonig** [comment]
Thanks for pointing out I should not be using ```:ID:```. I did not know about that. At the moment I don't have time to fix this and I also don't want to break functionality by changing the property name for anyone using this script currently. I'll keep this issue open and I will address it when I have some time.

As a workaround I suggest to use a separate file with the feed configuration, in which you don't save anything other than the feeds. I hope this helps you for the moment!

**Comment by leafac** [comment]
@remyhonig That's fine. I'm using the workaround you suggested. Thanks for the project.

**Comment by remyhonig** [comment]
Update: I'm rewriting this package using better techniques I learned recently which will fix this bug

**Comment by leafac** [comment]
That's great news! :smile:

**Comment by leafac** [comment]
I'm going to close this issue for two reasons:

1. You said you're going to rewrite elfeed-org so this would be out of scope.
2. I'm no longer using elfeed-org. What I have instead is an entry like the
   following in the middle of a huge Org mode file:

   ```org
   *** Feeds
       :PROPERTIES:
       :CATEGORY: feeds
       :END:
   **** Category
   ***** http://example.com/feed
   ***** http://example.com/other-feed
   ***** Sub category
   ****** http://example.com/yet-other-feed
   ...
   ```

   Then, I setup the `elfeed-feeds` variable with the following Emacs Lisp code
   that I load on startup:

   ```elisp
   (require 'dash)
   (require 'url-parse)
   (require 'org)

   (defun leafac-elfeed-update-feeds ()
     "Update the `elfeed-feeds' variable based on a feed list kept
   in a Org Mode file."
     (interactive)
     (setq elfeed-feeds
           (--filter (url-type (url-generic-parse-url it))
                     (org-map-entries
                      '(org-get-heading t t)
                      "CATEGORY=\"feeds\"" 'agenda))))

   (leafac-elfeed-update-feeds)
   ```

   If I change the feed list and want to see the update right away, I just call
   `leafac-elfeed-update-feeds` by hand.

Thanks for your project and the inspiration!

**Comment by remyhonig** [comment]
Interesting approach. Thanks for updating this issue and the kind words!

**Comment by gour** [comment]
@leafac: Thank you for your comment and code snippet...I was having problem with elfeed-org setup (some recursive loading), but your solution works here. ;)

**Comment by remyhonig** [comment]
I just merged the rewrite of this package which should fix this bug.

**Comment by leafac** [comment]
@gour: I'm glad it was helpful to you.

@remyhonig: congratulations on the new release!

**Comment by leafac** [comment]
For people using my snippet above, please note the update on my comment.
