### ISSUE TITLE
Using elfeed-add-feed to populate elfeed.org

### ISSUE THREAD

**Issue by powerverwirrt** [remyhonig/elfeed-org#60]
Hello, Emacs and Elisp noob here. I love Elfeed and Elfeed Org makes it much easier to keep track of my feeds!

However, I was wondering whether there is a way I can use "M-x elfeed-add-feed" to automatically populate my elfeed.org file.

Right now it just creates a custom.el when I run it and I can't seem to find the variables I'd have to overwrite. Any pointers?

Thanks for the package!

**Comment by remyhonig** [comment]
Hi! I appreciate your thanks, you're welcome. But I don't think you can automatically populate an org file. The way it was intended is to create an org tree yourself and work from there.

**Comment by powerverwirrt** [comment]
Thanks for the quick response! I guess I was trying to make it too easy for myself, haha. If I come up with anything, I'll let you know but having this org file is definitely easier for keeping up with everything.

I wasn't sure whether I had overlooked something so I'm glad I got an answer anyway. Hope you have a good weekend!
