### ISSUE TITLE
elfeed-org Generates Symbol's function definition is void: s-match when reading elfeed.org file

### ISSUE THREAD

**Issue by jandrusk** [remyhonig/elfeed-org#83]
I just started receiving 'Symbol's function definition is void: s-match' in Emacs when attempting to load elfeed. I enabled debugging and noticed it's bombing out trying to parse my elfeed.org file.

Screenshot of debug error can be found at: https://imgur.com/a/gVKN5pa

**Comment by toregilhk** [comment]
I'm having the same issue.

It seems to me that the problem lies in line 292-294 of `elfeed.org`, that uses the functions `s-match` and `s-starts-with`, which appear to belong to the `s` library that was removed as a dependency in #81

**Comment by jandrusk** [comment]
Thanks @toregilhk for the fix and I tested it by manually applying your update and it resolves the issue. Hopefully the commit is accepted soon so the fix can get pushed to MELPA for others using this.

**Comment by sjLambda** [comment]
What does it take to make this fix appear in MELPA?

**Comment by hobbes** [comment]
you can manually apply the fix, it works. 

@remyhonig please merge this and publish to melpa, elfeed-org is unusable in its present state...

**Comment by LemonBreezes** [comment]
I have just made a PR #87 addressing this issue. Thanks for bringing this up. Hope the PR gets accepted soon.

**Comment by remyhonig** [comment]
My apologies, should be fixed now!

**Comment by remyhonig** [comment]
I muted most of my notification from github causing me to miss all this, now I re-enabled them and plan to respond much sooner next time.
